version: 2
updates:
  - package-ecosystem: npm
    target-branch: dev
    commit-message:
      prefix: build
    pull-request-branch-name:
      separator: '-'
    directories:
      - /
    schedule:
      interval: weekly
      day: wednesday
      time: '08:00'
      timezone: GMT
    groups:
      vitest:
        patterns:
          - '@vitest/*'
          - vitest
