branch_protection:
  restrictions:
    teams:
      - tools-release
  required_status_checks:
    checks:
      - context: NPM Scripts (14.x, test)
      - context: NPM Scripts (14.x, lint)
      - context: Pull Request Open Routine
branch_protection_override:
  dev:
    restrictions:
      teams:
        - tools-release
        - tools-review
