(() => {
  'use strict';

  module.exports = {
    'unicorn/better-regex': ['error'],
    'unicorn/catch-error-name': [ 'error', { name: 'err' }],
    'unicorn/consistent-function-scoping': ['error'],
    'unicorn/custom-error-definition': ['error'],
    'unicorn/empty-brace-spaces': ['error'],
    'unicorn/error-message': ['error'],
    'unicorn/filename-case': ['error'],
    'unicorn/new-for-builtins': ['error'],
    'unicorn/no-abusive-eslint-disable': ['error'],
    'unicorn/no-array-push-push': ['error'],
    'unicorn/no-document-cookie': ['error'],
    'unicorn/no-for-loop': ['error'],
    'unicorn/no-hex-escape': ['error'],
    'unicorn/no-instanceof-array': ['error'],
    'unicorn/no-new-array': ['error'],
    'unicorn/no-process-exit': ['error'],
    'unicorn/no-thenable': ['error'],
    'unicorn/no-this-assignment': ['error'],
    'unicorn/no-unsafe-regex': ['error'],
    'unicorn/no-unused-properties': ['error'],
    'unicorn/no-useless-promise-resolve-reject': ['error'],
    'unicorn/no-useless-undefined': ['error'],
    'unicorn/no-zero-fractions': ['error'],
    'unicorn/number-literal-case': ['error'],
    'unicorn/prefer-array-flat-map': ['error'],
    'unicorn/prefer-array-flat': ['error'],
    'unicorn/prefer-date-now': ['error'],
    'unicorn/prefer-dom-node-append': ['error'],
    'unicorn/prefer-dom-node-dataset': ['error'],
    'unicorn/prefer-dom-node-remove': ['error'],
    'unicorn/prefer-dom-node-text-content': ['error'],
    'unicorn/prefer-keyboard-event-key': ['error'],
    'unicorn/prefer-modern-dom-apis': ['error'],
    // turn this back on when we move to pure ESM
    'unicorn/prefer-node-protocol': ['off'],
    'unicorn/prefer-number-properties': ['error'],
    'unicorn/prefer-query-selector': ['error'],
    'unicorn/prefer-regexp-test': ['error'],
    'unicorn/prefer-string-replace-all': ['error'],
    'unicorn/prefer-string-slice': ['error'],
    'unicorn/prefer-string-starts-ends-with': ['error'],
    'unicorn/prefer-string-trim-start-end': ['error'],
    'unicorn/prefer-type-error': ['error'],
    'unicorn/require-array-join-separator': ['error'],
    'unicorn/require-number-to-fixed-digits-argument': ['error'],
    'unicorn/throw-new-error': ['error'],
  };
})();
