export default {
  'n/callback-return': [
    'error',
    [
      'callback',
      'cb',
      'done',
      'next',
    ],
  ],
  'n/file-extension-in-import': [ 'error', 'always' ],
  'n/handle-callback-err': ['error'],
  'n/no-deprecated-api': ['error'],
  'n/no-extraneous-import': ['error'],
  'n/no-missing-import': ['error'],
  'n/no-path-concat': ['error'],
  'n/no-sync': ['error'],
  'n/no-unpublished-bin': ['error'],
  'n/no-unpublished-import': ['error'],
  'n/no-unsupported-features/es-builtins': ['error'],
  'n/no-unsupported-features/es-syntax': ['error'],
  'n/no-unsupported-features/node-builtins': ['error'],
  'n/prefer-global/buffer': [ 'error', 'always' ],
  'n/prefer-global/console': [ 'error', 'always' ],
  'n/prefer-global/process': [ 'error', 'always' ],
  'n/prefer-global/text-decoder': [ 'error', 'never' ],
  'n/prefer-global/text-encoder': [ 'error', 'never' ],
  'n/prefer-global/url-search-params': [ 'error', 'never' ],
  'n/prefer-global/url': [ 'error', 'never' ],
  'n/prefer-node-protocol': ['error'],
  'n/prefer-promises/dns': ['error'],
  'n/prefer-promises/fs': ['error'],
};
