---
name: Asana

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pull-request:
    if: ${{ 'pull_request' == github.event_name }}
    name: Pull Request Routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Asana Pull Request Routine
        uses: ./.github/actions/composites/asana-pr
        with:
          asana-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-user: ${{ secrets.GH_USER_NAME }}

  complete-tasks:
    if: ${{ 'push' == github.event_name }}
    name: Complete Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Asana Complete Tasks Routine
        uses: ./.github/actions/composites/asana-complete-tasks
        with:
          asana-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
