---
name: Build

on: push

jobs:
  configure:
    name: Configure Environment
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.configure.outputs.config }}
      deployments: ${{ steps.configure.outputs.deployments }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Configure
        id: configure
        uses: ./.github/actions/composites/configure
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  npm:
    name: NPM Scripts
    runs-on: ubuntu-latest
    needs:
      - configure
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.configure.outputs.config).node.supports }}
        script:
          - test
          - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          node-version: ${{ matrix.node-version }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: npm run ${{ matrix.script }}
        uses: ./.github/actions/composites/npm-script
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          node-version: ${{ matrix.node-version }}
          script: ${{ matrix.script }}
