---
name: Build

on: push

jobs:
  npm:
    name: NPM Scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        script: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - run: npm run ${{ matrix.script }} --if-present

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck
        shell: bash
        run: |
          if test "$(find . -name "*.sh" | grep -v node_modules | wc -c)" -ne 0
          then
            find . -name "*.sh" | grep -v node_modules | xargs shellcheck
          fi
