---
name: Build

on: push

jobs:
  npm:
    name: NPM Scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        script: [test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - run: npm run ${{ matrix.script }} --if-present
