---
name: NPM Publish

on:
  release:
    types:
      - created

jobs:
  npm-publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: NPM Setup
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}
          //npm.pkg.github.com/:_authToken=${{ secrets.GH_ACCESS_TOKEN }}
          @simplesenseio:registry=https://npm.pkg.github.com" >> "${GITHUB_WORKSPACE}/.npmrc"

      - name: NPM Install
        run: npm install

      - name: NPM Publish
        run: npm publish

      - name: NPM Teardown
        run: rm -f "${GITHUB_WORKSPACE}/.npmrc"
