---
name: Pull Request

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main

jobs:
  pull-request-open:
    if: ${{ 'pull_request' == github.event_name }}
    name: Pull Request Open Routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Open Routine
        uses: ./.github/actions/composites/github-pr-open
        with:
          asana-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-user: ${{ secrets.GH_USER_NAME }}

  pull-request-merge:
    if: ${{ 'push' == github.event_name }}
    name: Pull Request Merge Routine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Merge Routine
        uses: ./.github/actions/composites/github-pr-merge
        with:
          asana-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
