---
name: Rebase Main

on:
  push:
    branches:
      - main

jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
          ref: main
          fetch-depth: 0

      - name: Install Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Rebase & Push or Create PR
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          MY_GIT_EMAIL: ${{ secrets.GH_USER_EMAIL }}
          MY_GIT_NAME: ${{ secrets.GH_USER_NAME }}
        id: dev
        run: node "${GITHUB_WORKSPACE}/.github/workflows/scripts/rebase-main/rebase-main.js"
        shell: bash
