---
name: GitHub Repository Settings

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Repository Settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Repository Settings Routine
        uses: ./.github/actions/composites/github-repository-settings
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
