---
name: Schedule

on:
  schedule:
    # midnight or 11 PM mountain time - depends on MST vs MDT
    # purposely don't do * for the day
    # so our composites can choose if/when to run
    - cron: '0 7 * * 0'
    - cron: '0 7 * * 1'
    - cron: '0 7 * * 2'
    - cron: '0 7 * * 3'
    - cron: '0 7 * * 4'
    - cron: '0 7 * * 5'
    - cron: '0 7 * * 6'

jobs:
  configure:
    name: Configure Environment
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.configure.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Configure
        id: configure
        uses: ./.github/actions/composites/configure
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}

  cron:
    name: Run cron
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          config: ${{ needs.configure.outputs.config }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Schedule Routine
        uses: ./.github/actions/composites/cron-schedule
        with:
          config: ${{ needs.configure.outputs.config }}
          github-email: ${{ secrets.GH_USER_EMAIL }}
          github-ssh-public-key: ${{ secrets.GH_SSH_PUBLIC_KEY }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-user: ${{ secrets.GH_USER_NAME }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
