---
name: Test Coverage

on: pull_request

env:
  NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_READ_TOKEN }}

jobs:
  configure:
    name: Configure Environment
    runs-on: ubuntu-latest
    outputs:
      si_config: ${{ steps.configure.outputs.si_config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Configure
        id: configure
        uses: ./.github/actions/composites/configure

  coverage:
    name: Comment on Pull Request
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Shared Actions
        uses: ./.github/workflows/composites/shared-actions
        with:
          config: ${{ needs.configure.outputs.si_config }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
          ssh-key: ${{ secrets.GH_SSH_PRIVATE_KEY }}

      - name: Jest Coverage Routine
        uses: ./.github/actions/composites/jest-coverage
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          github-user: ${{ secrets.GH_USER_NAME }}
          node-token: ${{ secrets.GH_NPM_READ_TOKEN }}
